version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    env_file:
      - .env
    volumes:
      - ./api:/api-db
      - ./alembic:/alembic-db
    ports:
      - "8000:8000"
    command: bash -c "alembic -c $ALEMBIC_CONFIG upgrade head && uvicorn api.main:app --host 0.0.0.0 --port 8000"