services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: tasks_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  

  backend:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    env_file:
      - .env
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash -c "alembic -c ./alembic.ini upgrade head && uvicorn api.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data: