services:
  db_dev:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: tasks_db
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"  

  db_test:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: tasks_test_db
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    ports:
      - "5433:5432"  

  backend:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    env_file:
      - .env
    volumes:
      - ./api:/api
      - ./migrations:/migrations
    ports:
      - "8000:8000"
    depends_on:
      - db_dev
      - db_test
    command: bash -c "alembic upgrade head && uvicorn api.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data_dev:
  postgres_data_test: