version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.12.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r backend/requirements.txt
      - run:
          name: Execute tests
          command: |
            . venv/bin/activate
            pytest api/tests/

  build:
    docker:
      - image: circleci/python:3.12.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t task-manager-backend ./api
      # - run:
      #     name: Push on dockerhub
      #     command: |
      #       docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      #       docker tag task-manager-backend $DOCKER_USERNAME/task-manager-backend:latest
      #       docker push $DOCKER_USERNAME/task-manager-backend:latest

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test