# Utiliser l'image officielle Python comme base
FROM python:3.12

WORKDIR /

COPY ./api /api
COPY ./alembic.ini /alembic.ini
COPY ./alembic /alembic

RUN pip install --no-cache-dir -r /api/requirements.txt

EXPOSE 8000
