name: CI for Task Manager

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: tasks_db
        ports:
          - 5432:5432
        options: > 
          --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

      # Step 4: Set up environment variables
      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgresql://postgres:mysecretpassword@localhost:5432/tasks_db" >> $GITHUB_ENV

      # Step 5: Apply database migrations
      - name: Run Alembic migrations
        run: |
          alembic -c alembic.ini upgrade head

      # Step 6: Run tests
      - name: Run tests with pytest
        run: |
          pytest --maxfail=5 --disable-warnings